/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.3.0
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.parallelstack.rsearch.model;

import com.parallelstack.rsearch.model.AlgorithmSuccessAlgorithmResults;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class AlgorithmSuccess {
  
  @SerializedName("algorithm_results")
  private AlgorithmSuccessAlgorithmResults algorithmResults = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public AlgorithmSuccessAlgorithmResults getAlgorithmResults() {
    return algorithmResults;
  }
  public void setAlgorithmResults(AlgorithmSuccessAlgorithmResults algorithmResults) {
    this.algorithmResults = algorithmResults;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlgorithmSuccess algorithmSuccess = (AlgorithmSuccess) o;
    return (this.algorithmResults == null ? algorithmSuccess.algorithmResults == null : this.algorithmResults.equals(algorithmSuccess.algorithmResults));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.algorithmResults == null ? 0: this.algorithmResults.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlgorithmSuccess {\n");
    
    sb.append("  algorithmResults: ").append(algorithmResults).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
