/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.3.0
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.parallelstack.rsearch.model;

import com.parallelstack.rsearch.model.DeleteIndexSuccessIndex;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class DeleteDocumentSuccess {
  
  @SerializedName("document")
  private DeleteIndexSuccessIndex document = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public DeleteIndexSuccessIndex getDocument() {
    return document;
  }
  public void setDocument(DeleteIndexSuccessIndex document) {
    this.document = document;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteDocumentSuccess deleteDocumentSuccess = (DeleteDocumentSuccess) o;
    return (this.document == null ? deleteDocumentSuccess.document == null : this.document.equals(deleteDocumentSuccess.document));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.document == null ? 0: this.document.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteDocumentSuccess {\n");
    
    sb.append("  document: ").append(document).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
