/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.parallelstack.rsearch.model;

import com.parallelstack.rsearch.model.GetIndexesFailureIndexes;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GetDocumentsFailure {
  
  @SerializedName("documents")
  private GetIndexesFailureIndexes documents = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public GetIndexesFailureIndexes getDocuments() {
    return documents;
  }
  public void setDocuments(GetIndexesFailureIndexes documents) {
    this.documents = documents;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDocumentsFailure getDocumentsFailure = (GetDocumentsFailure) o;
    return (this.documents == null ? getDocumentsFailure.documents == null : this.documents.equals(getDocumentsFailure.documents));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.documents == null ? 0: this.documents.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDocumentsFailure {\n");
    
    sb.append("  documents: ").append(documents).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
