/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.parallelstack.rsearch.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GetIndexesSuccessIndexesMetadata {
  
  @SerializedName("number_indexes")
  private BigDecimal numberIndexes = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getNumberIndexes() {
    return numberIndexes;
  }
  public void setNumberIndexes(BigDecimal numberIndexes) {
    this.numberIndexes = numberIndexes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetIndexesSuccessIndexesMetadata getIndexesSuccessIndexesMetadata = (GetIndexesSuccessIndexesMetadata) o;
    return (this.numberIndexes == null ? getIndexesSuccessIndexesMetadata.numberIndexes == null : this.numberIndexes.equals(getIndexesSuccessIndexesMetadata.numberIndexes));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.numberIndexes == null ? 0: this.numberIndexes.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetIndexesSuccessIndexesMetadata {\n");
    
    sb.append("  numberIndexes: ").append(numberIndexes).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
