/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.3.0
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.parallelstack.rsearch.model;

import com.parallelstack.rsearch.model.IndexesSuggestQuerySuggest;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class IndexesSuggestQuery {
  
  @SerializedName("suggest")
  private IndexesSuggestQuerySuggest suggest = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public IndexesSuggestQuerySuggest getSuggest() {
    return suggest;
  }
  public void setSuggest(IndexesSuggestQuerySuggest suggest) {
    this.suggest = suggest;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndexesSuggestQuery indexesSuggestQuery = (IndexesSuggestQuery) o;
    return (this.suggest == null ? indexesSuggestQuery.suggest == null : this.suggest.equals(indexesSuggestQuery.suggest));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.suggest == null ? 0: this.suggest.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndexesSuggestQuery {\n");
    
    sb.append("  suggest: ").append(suggest).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
