/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.3.0
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.parallelstack.rsearch.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SearchSuccessSearchResultsMetadata {
  
  @SerializedName("number_search_results")
  private BigDecimal numberSearchResults = null;
  @SerializedName("query")
  private String query = null;
  @SerializedName("aggregated")
  private Object aggregated = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getNumberSearchResults() {
    return numberSearchResults;
  }
  public void setNumberSearchResults(BigDecimal numberSearchResults) {
    this.numberSearchResults = numberSearchResults;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getQuery() {
    return query;
  }
  public void setQuery(String query) {
    this.query = query;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getAggregated() {
    return aggregated;
  }
  public void setAggregated(Object aggregated) {
    this.aggregated = aggregated;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchSuccessSearchResultsMetadata searchSuccessSearchResultsMetadata = (SearchSuccessSearchResultsMetadata) o;
    return (this.numberSearchResults == null ? searchSuccessSearchResultsMetadata.numberSearchResults == null : this.numberSearchResults.equals(searchSuccessSearchResultsMetadata.numberSearchResults)) &&
        (this.query == null ? searchSuccessSearchResultsMetadata.query == null : this.query.equals(searchSuccessSearchResultsMetadata.query)) &&
        (this.aggregated == null ? searchSuccessSearchResultsMetadata.aggregated == null : this.aggregated.equals(searchSuccessSearchResultsMetadata.aggregated));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.numberSearchResults == null ? 0: this.numberSearchResults.hashCode());
    result = 31 * result + (this.query == null ? 0: this.query.hashCode());
    result = 31 * result + (this.aggregated == null ? 0: this.aggregated.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchSuccessSearchResultsMetadata {\n");
    
    sb.append("  numberSearchResults: ").append(numberSearchResults).append("\n");
    sb.append("  query: ").append(query).append("\n");
    sb.append("  aggregated: ").append(aggregated).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
