/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.parallelstack.rsearch.model;

import java.math.BigDecimal;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SuggestQuerySuggest {
  
  @SerializedName("query")
  private String query = null;
  @SerializedName("fields")
  private List<String> fields = null;
  @SerializedName("fuzzy")
  private BigDecimal fuzzy = null;
  @SerializedName("size")
  private BigDecimal size = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getQuery() {
    return query;
  }
  public void setQuery(String query) {
    this.query = query;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getFields() {
    return fields;
  }
  public void setFields(List<String> fields) {
    this.fields = fields;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getFuzzy() {
    return fuzzy;
  }
  public void setFuzzy(BigDecimal fuzzy) {
    this.fuzzy = fuzzy;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getSize() {
    return size;
  }
  public void setSize(BigDecimal size) {
    this.size = size;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SuggestQuerySuggest suggestQuerySuggest = (SuggestQuerySuggest) o;
    return (this.query == null ? suggestQuerySuggest.query == null : this.query.equals(suggestQuerySuggest.query)) &&
        (this.fields == null ? suggestQuerySuggest.fields == null : this.fields.equals(suggestQuerySuggest.fields)) &&
        (this.fuzzy == null ? suggestQuerySuggest.fuzzy == null : this.fuzzy.equals(suggestQuerySuggest.fuzzy)) &&
        (this.size == null ? suggestQuerySuggest.size == null : this.size.equals(suggestQuerySuggest.size));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.query == null ? 0: this.query.hashCode());
    result = 31 * result + (this.fields == null ? 0: this.fields.hashCode());
    result = 31 * result + (this.fuzzy == null ? 0: this.fuzzy.hashCode());
    result = 31 * result + (this.size == null ? 0: this.size.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SuggestQuerySuggest {\n");
    
    sb.append("  query: ").append(query).append("\n");
    sb.append("  fields: ").append(fields).append("\n");
    sb.append("  fuzzy: ").append(fuzzy).append("\n");
    sb.append("  size: ").append(size).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
