/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.pstack.rsearch.model;

import com.pstack.rsearch.model.GetDocTypeSuccessDocumentType;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class GetDocTypeSuccess implements Serializable {
  
  @SerializedName("document_type")
  private GetDocTypeSuccessDocumentType documentType = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public GetDocTypeSuccessDocumentType getDocumentType() {
    return documentType;
  }
  public void setDocumentType(GetDocTypeSuccessDocumentType documentType) {
    this.documentType = documentType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDocTypeSuccess getDocTypeSuccess = (GetDocTypeSuccess) o;
    return (this.documentType == null ? getDocTypeSuccess.documentType == null : this.documentType.equals(getDocTypeSuccess.documentType));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.documentType == null ? 0: this.documentType.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDocTypeSuccess {\n");
    
    sb.append("  documentType: ").append(documentType).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
