/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.pstack.rsearch.model;

import com.pstack.rsearch.model.SearchSuccessSuggestResults;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class SearchSuccess implements Serializable {
  
  @SerializedName("suggest_results")
  private SearchSuccessSuggestResults suggestResults = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public SearchSuccessSuggestResults getSuggestResults() {
    return suggestResults;
  }
  public void setSuggestResults(SearchSuccessSuggestResults suggestResults) {
    this.suggestResults = suggestResults;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchSuccess searchSuccess = (SearchSuccess) o;
    return (this.suggestResults == null ? searchSuccess.suggestResults == null : this.suggestResults.equals(searchSuccess.suggestResults));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.suggestResults == null ? 0: this.suggestResults.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchSuccess {\n");
    
    sb.append("  suggestResults: ").append(suggestResults).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
