/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.pstack.rsearch.model;

import java.math.BigDecimal;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class SearchQuerySearchAggregations implements Serializable {
  
  @SerializedName("field_name")
  private String fieldName = null;
  public enum AggTypeEnum {
     term,  range,  histogram,  location, 
  };
  @SerializedName("agg_type")
  private AggTypeEnum aggType = null;
  @SerializedName("term_agg_size")
  private BigDecimal termAggSize = null;
  @SerializedName("range")
  private List<Object> range = null;
  @SerializedName("origin")
  private List<Object> origin = null;
  @SerializedName("buckets")
  private BigDecimal buckets = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getFieldName() {
    return fieldName;
  }
  public void setFieldName(String fieldName) {
    this.fieldName = fieldName;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public AggTypeEnum getAggType() {
    return aggType;
  }
  public void setAggType(AggTypeEnum aggType) {
    this.aggType = aggType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getTermAggSize() {
    return termAggSize;
  }
  public void setTermAggSize(BigDecimal termAggSize) {
    this.termAggSize = termAggSize;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Object> getRange() {
    return range;
  }
  public void setRange(List<Object> range) {
    this.range = range;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Object> getOrigin() {
    return origin;
  }
  public void setOrigin(List<Object> origin) {
    this.origin = origin;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getBuckets() {
    return buckets;
  }
  public void setBuckets(BigDecimal buckets) {
    this.buckets = buckets;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchQuerySearchAggregations searchQuerySearchAggregations = (SearchQuerySearchAggregations) o;
    return (this.fieldName == null ? searchQuerySearchAggregations.fieldName == null : this.fieldName.equals(searchQuerySearchAggregations.fieldName)) &&
        (this.aggType == null ? searchQuerySearchAggregations.aggType == null : this.aggType.equals(searchQuerySearchAggregations.aggType)) &&
        (this.termAggSize == null ? searchQuerySearchAggregations.termAggSize == null : this.termAggSize.equals(searchQuerySearchAggregations.termAggSize)) &&
        (this.range == null ? searchQuerySearchAggregations.range == null : this.range.equals(searchQuerySearchAggregations.range)) &&
        (this.origin == null ? searchQuerySearchAggregations.origin == null : this.origin.equals(searchQuerySearchAggregations.origin)) &&
        (this.buckets == null ? searchQuerySearchAggregations.buckets == null : this.buckets.equals(searchQuerySearchAggregations.buckets));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.fieldName == null ? 0: this.fieldName.hashCode());
    result = 31 * result + (this.aggType == null ? 0: this.aggType.hashCode());
    result = 31 * result + (this.termAggSize == null ? 0: this.termAggSize.hashCode());
    result = 31 * result + (this.range == null ? 0: this.range.hashCode());
    result = 31 * result + (this.origin == null ? 0: this.origin.hashCode());
    result = 31 * result + (this.buckets == null ? 0: this.buckets.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchQuerySearchAggregations {\n");
    
    sb.append("  fieldName: ").append(fieldName).append("\n");
    sb.append("  aggType: ").append(aggType).append("\n");
    sb.append("  termAggSize: ").append(termAggSize).append("\n");
    sb.append("  range: ").append(range).append("\n");
    sb.append("  origin: ").append(origin).append("\n");
    sb.append("  buckets: ").append(buckets).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
