/**
 * ParallelStack RSearch API
 * REST API Specification for ParallelStack RSearch API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: team@parallelstack.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.pstack.rsearch.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class SearchSuccessSuggestResultsMetadata implements Serializable {
  
  @SerializedName("number_search_results")
  private BigDecimal numberSearchResults = null;
  @SerializedName("query")
  private String query = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getNumberSearchResults() {
    return numberSearchResults;
  }
  public void setNumberSearchResults(BigDecimal numberSearchResults) {
    this.numberSearchResults = numberSearchResults;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getQuery() {
    return query;
  }
  public void setQuery(String query) {
    this.query = query;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchSuccessSuggestResultsMetadata searchSuccessSuggestResultsMetadata = (SearchSuccessSuggestResultsMetadata) o;
    return (this.numberSearchResults == null ? searchSuccessSuggestResultsMetadata.numberSearchResults == null : this.numberSearchResults.equals(searchSuccessSuggestResultsMetadata.numberSearchResults)) &&
        (this.query == null ? searchSuccessSuggestResultsMetadata.query == null : this.query.equals(searchSuccessSuggestResultsMetadata.query));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.numberSearchResults == null ? 0: this.numberSearchResults.hashCode());
    result = 31 * result + (this.query == null ? 0: this.query.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchSuccessSuggestResultsMetadata {\n");
    
    sb.append("  numberSearchResults: ").append(numberSearchResults).append("\n");
    sb.append("  query: ").append(query).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
